name = "TableTransforms"
uuid = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ScientificTypes = "2.3"
Tables = "1.6"
julia = "1"