name = "TableTransforms"
uuid = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "1.7.3"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NelderMead = "2f6b4ddb-b4ff-44c0-b59b-2ab99302f970"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
TransformsBase = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"

[compat]
AbstractTrees = "0.4"
CategoricalArrays = "0.10"
Distributions = "0.25"
NelderMead = "0.4.0"
PrettyTables = "1.3, 2"
ScientificTypes = "2.3, 3.0"
StatsBase = "0.33"
Tables = "1.6"
Transducers = "0.4"
TransformsBase = "0.1"
julia = "1.6"
